source_base_dir: ~/CERN/ntuples/fastframes-new      # no trailing '/'!!!
target_base_dir: ~/CERN/lq-asym-new/friend_ntuples/output/friend/    # yes trailing '/'!!!
model_path: ~/CERN/lq-asym-new/friend_ntuples/model.py
trex_config: ./configs/training-2500.config
region: tau-pt-0
branch_name: probs_LQ
batch_size: 5000
model: transformers/transformer-3
