trex_config: ./configs/training.config
region: "tau-pt-0"
output_path: "output"
features: ./features/all.yaml
categorical_features: ./features/categorical.yaml
array_features: ./features/array.yaml
invalid_values: ./features/invalid.yaml
n_jets: 1
samples:
  - WtZ
  - ttWZ
  - ttgamma
  - VV
  - SingleTop
  - ttW
  - ttZ
  - ttH
  - Vgamma
  - threeTop
  - ttWH
  - tZ
  - ttWW
  - LQ
  - ttZZ
  - ttHH
  - fourTop
  - VH
