trex_config: ./configs/training.config
region: "taus-pt-0"
output_path: "output"
features: ./features/all.yaml
categorical_features: ./features/categorical.yaml
array_features: ./features/array.yaml
invalid_values: ./features/invalid.yaml
n_jets: 2
samples:
  - ttZZ
  - ttgamma
  - tZ
  - VH
  - ttbar
  - fourTop
  - Zjets
  - Wjets
  - ttW
  - ttWZ
  - WtZ
  - ttHH
  - threeTop
  - LQ
  - ttWH
  - ttH
  - Vgamma
  - ttWW
  - VVV
  - ttZ
  - VV
  - SingleTop
